name: Code Quality

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # Allow manual trigger

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Check TypeScript compilation
      run: npm run compile

  format-check:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      
    - name: Check if code is formatted
      shell: bash
      run: |
        # Run lint fix to see if any changes are needed
        npm run lint:fix
        # Only check for changes in source files, ignore node_modules
        if [ -n "$(git status --porcelain src/)" ]; then
          echo "Source code is not properly formatted. Please run 'npm run lint:fix'"
          git diff src/
          exit 1
        else
          echo "Code is properly formatted"
        fi